# local dev environment
logging:
  level:
#    root: DEBUG
    de.neebs.aiwithjava.control: DEBUG
#    org.springframework.cloud.openfeign: DEBUG
management:
  server:
    port: 4467
server:
  port: 8081
  error:
    include-message: always
app:
  ai:
    python:
      url: http://localhost:5001
