openapi: 3.0.2
info:
  title: ai-with-java
  version: 1.0.0
  contact:
    name: Thomas Neeb
    email: thomas.neeb@nttdata.com
paths:
  /instances:
    post:
      operationId: createInstance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstanceConfiguration'
      responses:
        '201':
          description: Returns the id of the created instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstanceId'
  /instances/{instanceId}:
    parameters:
      - name: instanceId
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: getInstance
      responses:
        '200':
          description: Returns the instance configuration
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/InstanceId'
  /instances/{instanceId}/predictions:
    parameters:
      - name: instanceId
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: predict
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Observation3D'
      responses:
        '200':
          description: Returns the prediction for the given input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelOutput'
  /instance/{instanceId}/trainings:
    parameters:
      - name: instanceId
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: train
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TrainingData3D'
      responses:
        '204':
          description: Trained data successfully
  /instance/{instanceId}/copies:
    parameters:
      - name: instanceId
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: copy
      responses:
        '201':
          description: Returns the id of the created instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstanceId'
    put:
      operationId: copyParams
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstanceId'
      responses:
        '204':
          description: Returns the id of the created instance
components:
  schemas:
    InstanceConfiguration:
      type: object
      properties:
        saveFrequency:
          type: integer
    Observation1D:
      type: array
      items:
        type: number
        format: double
    Observation2D:
      type: array
      items:
        type: array
        items:
          type: number
          format: double
    Observation3D:
      type: array
      items:
        type: array
        items:
          type: array
          items:
            type: number
            format: double
    TrainingData1D:
      type: object
      properties:
        observation:
          $ref: '#/components/schemas/Observation1D'
        output:
          $ref: '#/components/schemas/ModelOutput'
        action:
          type: integer
    TrainingData2D:
      type: object
      properties:
        observation:
          $ref: '#/components/schemas/Observation2D'
        output:
          $ref: '#/components/schemas/ModelOutput'
        action:
          type: integer
    TrainingData3D:
      type: object
      properties:
        observation:
          $ref: '#/components/schemas/Observation3D'
        output:
          $ref: '#/components/schemas/ModelOutput'
        action:
          type: integer
    ModelOutput:
      type: array
      items:
        type: number
        format: double
    InstanceId:
      type: object
      properties:
        instanceId:
          type: string